version: "3.9"
services:
 mssql-database:
  container_name: jupiter-mssql-server
  image: "mcr.microsoft.com/mssql/server"
  ports: 
   - "1433:1433"
  environment:
   SA_PASSWORD: "jupiter-pwd"
   ACCEPT_EULA: "Y"
  restart: always
 azurite:
  image: mcr.microsoft.com/azure-storage/azurite
  container_name: jupiter-azurite
  hostname: azurite
  ports:
    - "10000:10000"
    - "10001:10001"
  restart: always