version: "3.9"
services:
 mssql:
  container_name: jupiter-mssql-server
  image: "mcr.microsoft.com/mssql/server"
  ports: 
   - "1433:1433"
  environment:
   SA_PASSWORD: "jupiter-pwd"
   ACCEPT_EULA: "Y"
  restart: always
 azurite:
  image: mcr.microsoft.com/azure-storage/azurite
  container_name: jupiter-azurite
  hostname: azurite
  ports:
    - "10000:10000"
    - "10001:10001"
  restart: always
 rabbitmq:
  image: rabbitmq:3-management
  container_name: jupiter_rabbitmq
  hostname: rabbitmq
  environment:
    RABBITMQ_DEFAULT_USER: "jupiter"
    RABBITMQ_DEFAULT_PASS: "jupiter-pwd"
  ports:
    - "5672:5672"
    - "15672:15672"
  restart: always
 redis:
  image: redis
  container_name: jupiter_redis
  command: redis-server --appendonly yes --requirepass jupiter-pwd
  ports:
    - 6379:6379
  restart: always
 #cosmosdb:
   #image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
   #container_name: jupiter_cosmosdb
   #restart: always
   #environment:
    #AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
    #AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: 10
    #AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: "${IPADDR}"
   #ports:
    #- "8081:8081"